package com.example.springboot.docker.model;

//import org.junit.jupiter.api.Test;
//import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
//
//import com.example.springboot.docker.mysql.repository.BackupRepository;
//
//@DataJpaTest
//public class BackupTests {
//	@Autowired // This means to get the bean called backupRepository Which is auto-generated by Spring, we will use it to handle the data
//    private BackupRepository backupRepository;
//
//	@Test
//	public void testCreateBackup() {
//		Backup backup = new Backup("eclipse-workspace", "2020/10/17 10:16:30");
//		backupRepository.save(backup);
//	}
//
//}
