package com.example.springboot.docker.mysql.controller;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import com.example.springboot.docker.mysql.model.Backup;
import com.example.springboot.docker.mysql.repository.BackupRepository;

@RestController
public class BackupController {
	
    @Autowired // This means to get the bean called backupRepository Which is auto-generated by Spring, we will use it to handle the data
    private BackupRepository backupRepository;
	
	@PostMapping("/addBackup") // Map ONLY POST Requests
	public String saveBackup(@RequestBody Backup emp) {
		backupRepository.save(emp);
		return "Backup added successfully: "+emp.getId();
		
	}
	
	@GetMapping("/backups")
	public List<Backup> getBackups() {
		return backupRepository.findAll();
	}

	@GetMapping("/findBackup/{id}")
	public Optional<Backup> getBackup(@PathVariable Long id) {
		return backupRepository.findById(id);
	}
	
	@GetMapping("/deleteBackup/{id}")
	public String deleteBackup(@PathVariable Long id) {
		backupRepository.deleteById(id);
		return "Deleted Backup Successfully: "+id;
	}
	

}
